-- MySQL Script generated by MySQL Workbench
-- 05/17/17 22:14:53
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softn_gr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softn_gr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softn_gr` DEFAULT CHARACTER SET utf8 ;
USE `softn_gr` ;

-- -----------------------------------------------------
-- Table `softn_gr`.`Clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softn_gr`.`Clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(37) NOT NULL,
  `client_address` VARCHAR(37) NULL,
  `client_identification_document` VARCHAR(10) NOT NULL,
  `client_city` VARCHAR(37) NULL,
  `client_number_receipts` INT NULL DEFAULT 0,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softn_gr`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(37) NOT NULL,
  `product_price_unit` INT NOT NULL,
  `product_reference` VARCHAR(6) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Receipts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softn_gr`.`Receipts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receipt_type` VARCHAR(20) NOT NULL,
  `receipt_number` INT NULL,
  `receipt_date` DATETIME NOT NULL,
  `client_id` INT NOT NULL,
  PRIMARY KEY (`id`, `client_id`),
  INDEX `fk_Receipts_Clients_id` (`client_id` ASC),
  CONSTRAINT `fk_Receipts_Clients`
    FOREIGN KEY (`client_id`)
    REFERENCES `softn_gr`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Options`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softn_gr`.`Options` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `option_key` VARCHAR(45) NULL,
  `option_value` VARCHAR(45) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `option_key_UNIQUE` (`option_key` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Receipts_has_Products`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `softn_gr`.`Receipts_has_Products` (
  `receipt_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `receipt_product_unit` INT NOT NULL DEFAULT 1,
  PRIMARY KEY (`receipt_id`, `product_id`),
  INDEX `fk_Receipts_has_Products_Product_id` (`product_id` ASC),
  INDEX `fk_Receipts_has_Products_Receipt_id` (`receipt_id` ASC),
  CONSTRAINT `fk_Receipts_has_Products_Receipt`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `softn_gr`.`Receipts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipts_has_Products_Product`
    FOREIGN KEY (`product_id`)
    REFERENCES `softn_gr`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `softn_gr`.`Options`
-- -----------------------------------------------------
START TRANSACTION;
USE `softn_gr`;
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (1, 'option_name', 'Samuel Blankenship');
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (2, 'option_identification_document', '55588414J');
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (3, 'option_address', '1261 Aliquam Avenue');
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (4, 'option_phone_number', '1234567890');
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (5, 'option_web_site', 'http://www.softn.red/');
INSERT INTO `softn_gr`.`Options` (`id`, `option_key`, `option_value`) VALUES (6, 'option_iva', '21');

COMMIT;

