-- MySQL Script generated by MySQL Workbench
-- 04/15/17 17:30:40
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema softn_gr
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema softn_gr
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `softn_gr` DEFAULT CHARACTER SET utf8 ;
USE `softn_gr` ;

-- -----------------------------------------------------
-- Table `softn_gr`.`Clients`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softn_gr`.`Clients` ;

CREATE TABLE IF NOT EXISTS `softn_gr`.`Clients` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `client_name` VARCHAR(45) NULL,
  `client_address` VARCHAR(45) NULL,
  `client_identification_document` VARCHAR(45) NULL,
  `client_city` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softn_gr`.`Products` ;

CREATE TABLE IF NOT EXISTS `softn_gr`.`Products` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `product_name` VARCHAR(45) NULL,
  `product_price_unit` VARCHAR(45) NULL,
  `product_reference` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Receipts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softn_gr`.`Receipts` ;

CREATE TABLE IF NOT EXISTS `softn_gr`.`Receipts` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `receipt_type` VARCHAR(45) NULL,
  `receipt_number` VARCHAR(45) NULL,
  `receipt_date` VARCHAR(45) NULL,
  `Clients_id` INT NOT NULL,
  PRIMARY KEY (`id`, `Clients_id`),
  INDEX `fk_Receipts_Clients_idx` (`Clients_id` ASC),
  CONSTRAINT `fk_Receipts_Clients`
    FOREIGN KEY (`Clients_id`)
    REFERENCES `softn_gr`.`Clients` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Options`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softn_gr`.`Options` ;

CREATE TABLE IF NOT EXISTS `softn_gr`.`Options` (
)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `softn_gr`.`Receipts_has_Products`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `softn_gr`.`Receipts_has_Products` ;

CREATE TABLE IF NOT EXISTS `softn_gr`.`Receipts_has_Products` (
  `receipt_id` INT NOT NULL,
  `product_id` INT NOT NULL,
  `receipt_product_unit` INT NULL,
  PRIMARY KEY (`receipt_id`, `product_id`),
  INDEX `fk_Receipts_has_Products_Product_id` (`product_id` ASC),
  INDEX `fk_Receipts_has_Products_Receipt_id` (`receipt_id` ASC),
  CONSTRAINT `fk_Receipts_has_Products_Receipt`
    FOREIGN KEY (`receipt_id`)
    REFERENCES `softn_gr`.`Receipts` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Receipts_has_Products_Product`
    FOREIGN KEY (`product_id`)
    REFERENCES `softn_gr`.`Products` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
